name: Build and Deploy with Hugo

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Or specify a version like '0.110.0'

      - name: Build with Hugo
        run: hugo # Or hugo --minify if you want to minify

      - name: Print Working Directory
        run: pwd

      - name: List files in the public directory
        run: ls -l ./public # Hugo's default output directory is "public"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages # Or a custom name if needed (e.g., my-hugo-site)
          path: ./public      # Path to Hugo's default output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
    environment: production
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          # artifact-name: github-pages (implied if not specified)
          path: ./public # Must be the same path as in the upload step
